name: Update Calendar

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write  # 添加写入权限

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          
      - name: Setup directories
        run: |
          mkdir -p public
          
      - name: Download global calendar
        run: |
          response=$(curl -s "https://economic-calendar-lovat.vercel.app/api/generate")
          if echo "$response" | jq -e '.success == true' > /dev/null 2>&1; then
            echo "$response" | jq -r '.data' > public/economic-calendar.ics
          else
            echo "Error downloading global calendar: $response"
            exit 1
          fi
          
      - name: Download country calendars
        run: |
          download_calendar() {
            local country=$1
            local file="public/economic-calendar-$2.ics"
            local response=$(curl -s "https://economic-calendar-lovat.vercel.app/api/generate?country=$country")
            if echo "$response" | jq -e '.success == true' > /dev/null 2>&1; then
              echo "$response" | jq -r '.data' > "$file"
              echo "Successfully downloaded calendar for $2"
            else
              echo "Error downloading calendar for $2: $response"
              exit 1
            fi
          }

          # 下载各个国家的日历
          download_calendar "US" "united-states"
          download_calendar "CN" "china"
          download_calendar "EA" "eurozone"
          download_calendar "JP" "japan"
          download_calendar "UK" "united-kingdom"
          download_calendar "AU" "australia"
          download_calendar "DE" "germany"
          download_calendar "FR" "france"
          download_calendar "CA" "canada"
          download_calendar "CH" "switzerland"
          download_calendar "IT" "italy"
          download_calendar "NZ" "new-zealand"
          download_calendar "ES" "spain"
          download_calendar "KR" "south-korea"
          download_calendar "HK" "hong-kong"
          download_calendar "SG" "singapore"
          download_calendar "NO" "norway"
          download_calendar "SE" "sweden"
          
      - name: List files
        run: |
          ls -la public/
          
      - name: Update generation time
        run: |
          timestamp=$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')
          sed -i "s/最后更新时间：.*/最后更新时间：$timestamp/g" public/index.html
          
      - name: Commit and push if there are changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f public/*.ics
          git add public/index.html
          git commit -m "Update economic calendar" || exit 0
          git push

      - name: Trigger Vercel Deployment
        run: |
          curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deployment
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_wcseVHHfVb6Y2WDxDCKYVy17ainn/dmruzc4PPO"
          echo "Vercel deployment triggered successfully"
