name: Update Economic Calendar

on:
  schedule:
    - cron: '*/10 * * * *'  # 每10分钟运行一次
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write  # 添加写入权限

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Download and save calendar
        run: |
          # 下载日历内容并保存
          curl -o public/economic-calendar.ics https://economic-calendar-lovat.vercel.app/api/generate
          
          # 获取当前时间（北京时间）
          current_time=$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M')
          
          # 更新 index.html 中的生成时间
          sed -i "s/日历生成时间：.*。<\/p>/日历生成时间：$current_time。<\/p>/" public/index.html
          
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add public/economic-calendar.ics public/index.html
          git diff --staged --quiet || (git commit -m "chore: update calendar [skip ci]" && git push)
