name: Update Economic Calendar

on:
  schedule:
    - cron: '*/10 * * * *'  # 每10分钟运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  trigger-update:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Calendar Generation
        run: |
          curl -X GET https://economic-calendar-lovat.vercel.app/api/generate
          echo "Calendar generation triggered"
